name: secondsout
description: "Sistema de gestión deportiva para entrenadores y atletas."

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  firebase_storage: ^11.7.7

  syncfusion_flutter_charts: ^20.4.48
  # Base de datos local
  floor: ^1.5.0
  floor_annotation: ^1.5.0
  sqflite: ^2.3.3+1

  # Gestión de estado
  provider: ^6.1.5

  # Utilidades
  intl: ^0.18.1
  image_picker: ^0.8.9
  fluttertoast: ^8.2.2
  uuid: ^3.0.7
  shared_preferences: ^2.3.3

  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.5.0
  build_runner: ^2.4.11
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icono.png"
flutter:
  uses-material-design: true
  
